
'''
    1.1 First test suite - 
    1.2 Pytest.raises
    1.3 

    Fixtures 
    2.1 

'''

#1.1 first test suite 
def multiple_of_two(num):
    if num == 0:
        raise(ValueError)
    return num % 2 == 0

def test_numbers():
    assert multiple_of_two(2) is True
    # Write the "False" test below
    assert multiple_of_two(5) is False



#1.2 pytest.raises 
def multiple_of_two(num):
    if num == 0:
        raise(ValueError)
    return num % 2 == 0

def test_zero():    
  	# Add a context for an exception test here
    with pytest.raises(ValueError):
      	# Check zero input below
        multiple_of_two(0)



#1.3 - run the script - 1 (pytest run_the_script.py)
# Import the pytest library
import pytest

def multiple_of_two(num):
    if num == 0:
        raise(ValueError)
    return num % 2 == 0

def test_numbers():
    assert multiple_of_two(2) is True
    assert multiple_of_two(3) is False

def test_zero():    
    with pytest.raises(ValueError):
        multiple_of_two(0)



#1.4 - run the script 2 (pytest run_the_script.py -k "numbers")
# Import the pytest library
import pytest 

def multiple_of_two(num):
    if num == 0:
        raise(ValueError)
    return num % 2 == 0

def test_numbers():
    assert multiple_of_two(2) == True
    assert multiple_of_two(3) == False

def test_zero():    
    with pytest.raises(ValueError):
        multiple_of_two(0)



#1.5 an'@pytest.mark.xfai'l' that fails. 
def multiple_of_two(num):
    if num == 0:
        raise(ValueError)
    return num % 2 == 0

# Add the pytest marker decorator here
@pytest.mark.xfail
def test_fails():
    # Write any assert test that will fail
    assert multiple_of_two(5) == False



#1.6 an @pytest.mark.skipif(condition_string)
day_of_week = datetime.now().isoweekday()

def get_unique_values(lst):
    return list(set(lst))

condition_string = 'day_of_week == 6'
# Add the conditional skip marker and the string here
@pytest.mark.skipif(condition_string)
def test_function():
	# Complete the assertion tests here
    assert get_unique_values([1,2,3]) == [1,2,3]
    assert get_unique_values([1,2,3,1]) == [1,2,3]




#Fixtures 

#2.1 Fixtures 
# Import the pytest library
import pytest

# Define the fixture decorator
@pytest.fixture
# Name the fixture function
def prepare_data():
    return [i for i in range(10)]

# Create the tests
def test_elements(prepare_data):
    assert 9 in prepare_data
    assert 10 not in prepare_data


#2.2 - List with a custom length
#You already saw a list preparation implemented as a fixture. But what if you also want to customize the preparation process? 
# For example, one might want to set a custom length for a generated list. 
# You can implement it with chain fixture requests by making the "length" a separate fixture; let's call it list_length(). 
# In the end, you will have a test function that requests the list, and the list is then generated by requesting the list_length().

import pytest

# Define the fixture for returning the length
@pytest.fixture
def list_length():
    return 10

# Define the fixture for a list preparation
@pytest.fixture
def prepare_list(list_length):
    return [i for i in range(list_length)]

def test_9(prepare_list):
    assert 9 in prepare_list
    assert 10 not in prepare_list

#pytest name_of_file.py 




#2.3 - Auto add numbers
# Now you will practice declaring autouse. 
# At the start, you have an empty Python list. 
# And there is a function that adds some elements to it. 
# Add autouse to the add_numbers_to_list() fixture function, so you could use it without explicitly requesting from the test function. 
# And finally complete the assertion tests by checking if 1 is in init_list and if 9 is in init_list.

import pytest

@pytest.fixture
def init_list():
    return []

# Declare the fixture with autouse
@pytest.fixture(autouse=True)
def add_numbers_to_list(init_list):
    init_list.extend([i for i in range(10)])

# Complete the tests
def test_elements(init_list):
    assert 1 in init_list 
    assert 9 in init_lists






#2.4 - Data with teardown
#Teardowns help you to prevent memory leaks and other issues with the environment. 
# In this exercise, you will implement a teardown for the prepare_data() function and run the test at the end.

import pytest

@pytest.fixture
def prepare_data():
    data = [i for i in range(10)]
    # Return the data with the special keyword
    yield data
    # Clear the data list
    data.clear()
    # Delete the data variable
    del data

def test_elements(prepare_data):
    assert 9 in prepare_data
    assert 10 not in prepare_data




#2.5 - Read data with teardown
#This time instead of a list, you will deal with a pandas.
# DataFrame of pandas package. You have the pytest fixture to read the data, and you have to implement the teardown to clean it up.

import pytest
import pandas as pd

@pytest.fixture
def data():
    df = pd.read_csv('/usr/local/share/games.csv')
    # Return df with the special keyword
    yield df
    # Remove all rows in df
    df.drop(df.index, inplace=True)
    # Delete the df variable
    del df

def test_type(data):
    assert type(data) == pd.DataFrame

def test_shape(data):
    assert data.shape[0] == 1512



#3.1 - unit tests 

def factorial(n):
    if n == 0: return 1
    elif (type(n) == int):
        return n * factorial(n-1)
    else: return -1

# Test case: zero input
def test_zero():
	assert factorial(0) == 1

#3.2 

def factorial(n):
    if n == 0: return 1
    elif (type(n) == int):
        return n * factorial(n-1)
    else: return -1

# Test case: input of a wrong type
def test_str():
    assert factorial('5') == -1
    print('Test passed')

test_str()





# 3.3 Fixture to prepare the data
@pytest.fixture
def get_df():
    return pd.read_csv('https://assets.datacamp.com/production/repositories/6253/datasets/757c6cb769f7effc5f5496050ea4d73e4586c2dd/laptops_train.csv')

# Aggregation feature
def agg_with_sum(data, group_by_column, aggregate_column):
    return data.groupby(group_by_column)[aggregate_column].sum()

# Test function
def test_agg_feature(get_df):
    # Aggregate preparation
    aggregated = agg_with_sum(get_df, 'Manufacturer', 'Price')
    # Test the type of the aggregated
    assert type(aggregated) == pd.Series
    # Test the number of rows of the aggregated
    assert aggregated.shape[0] > 0
    # Test the data type of the aggregated
    assert aggregated.dtype in (int, float)




import pandas as pd
import pytest

# Fixture to read the dataframe
@pytest.fixture
def get_df():
    return pd.read_csv('https://assets.datacamp.com/production/repositories/6253/datasets/757c6cb769f7effc5f5496050ea4d73e4586c2dd/laptops_train.csv')

# Integration test function
def test_get_df(get_df):
    # Check the type
    assert type(get_df) == pd.DataFrame
    # Check the number of rows
    assert get_df.shape[0] > 0

    

"""  
Finding an element
Using the right data structure can significantly increase the performance of your code. 
For example, if you want to find a certain element in the data, you might want to choose between list and set.
In this exercise, you will implement performance tests with pytest to compare the speed of the in operator applied 
correspondingly to the two data structures: list and set. 

Instructions
Pass benchmark as an argument into the test functions.
Then call benchmark() in the test functions passing find() as the first argument.
"""

def create_list():
    return [i for i in range(1000)]
def create_set():
    return set([i for i in range(1000)])
def find(it, el=50):
    return el in it

# Write the performance test for a list
def test_list(benchmark):
    benchmark(find, it=create_list())
    
# Write the performance test for a set
def test_set(benchmark):
    benchmark(find, it=create_set())





"""
Speed of loops
Of course, set is better suited for searching elements. 
It is based on hashes, so you can expect constant complexity most of the time. 
But what about iterating over all the object's elements? 
Let's compare the speed of loop iteration over the elements of list and set with pytest and pytest-benchmark. 
The pytest package has already been imported.

Instructions
Add @benchmark decorator before the functions starting with iterate_.
Complete the loops in iterate_list and iterate_set.
"""
def test_list(benchmark):
	# Add decorator here
    @benchmark
    def iterate_list():
		# Complete the loop here
        for el in [i for i in range(1000)]:
            pass

def test_set(benchmark):
	# Add decorator here
    @benchmark
    def iterate_set():
        # Complete the loop here
        for el in {i for i in range(1000)}:
            pass



#Test assertTrue
def is_prime(num):
    if num == 1: return False
    up_limit = int(math.sqrt(num)) + 1
    for i in range(2, up_limit):
        if num % i == 0:
            return False
    return True

class TestSuite(unittest.TestCase):
    def test_is_prime(self):
        # Check that 17 is prime
        self.assertTrue(is_prime(17))

#part2
class TestSuite(unittest.TestCase):
    def test_is_prime(self):
        # Check that 6 is not prime
        self.assertFalse(is_prime(6))